var arAsproOptions = window[solutionName] = ({
	"SITE_DIR" : "/",
	"SITE_ID" : "s1",
	"SITE_TEMPLATE_PATH" : "/bitrix/templates/aspro_max",
	"SITE_ADDRESS" : "region-rus.ru",
	"FORM" : ({
		"ASK_FORM_ID" : "ASK",
		"SERVICES_FORM_ID" : "SERVICES",
		"FEEDBACK_FORM_ID" : "FEEDBACK",
		"CALLBACK_FORM_ID" : "CALLBACK",
		"RESUME_FORM_ID" : "RESUME",
		"TOORDER_FORM_ID" : "TOORDER"
	}),
	"PAGES" : ({
		"CATALOG_PAGE_URL" : "/catalog/",
		"COMPARE_PAGE_URL" : "/catalog/compare.php",
		"SEARCH_PAGE_URL" : "/search/",
		"BASKET_PAGE_URL" : "/basket/",
		"SHARE_BASKET_PAGE_URL" : "/sharebasket/",
		"ORDER_PAGE_URL" : "/order/",
		"PERSONAL_PAGE_URL" : "/personal/",
		"SUBSCRIBE_PAGE_URL" : "/personal/subscribe/",
	}),
	"PRICES" : ({
		"MIN_PRICE" : "0",
	}),
	"THEME" : ({
		'THEME_SWITCHER' : 'N',
		'BIGBANNER_MOBILE': '3',
		'BASE_COLOR' : 'CUSTOM',
		'BASE_COLOR_CUSTOM' : '0069bb',
		'LOGO_IMAGE' : '/upload/CMax/a91/a9175f0fca7b0ba0cb9b4a02c14ed1c0.svg',
		'LOGO_IMAGE_LIGHT' : '',
		'TOP_MENU_FIXED' : 'Y',
		'COLORED_LOGO' : 'N',
		'COMPACT_FOOTER_MOBILE' : 'Y',
		'SIDE_MENU' : 'LEFT',
		'SCROLLTOTOP_TYPE' : 'ROUND_COLOR',
		'SCROLLTOTOP_POSITION' : 'PADDING',
		'SCROLLTOTOP_POSITION_RIGHT' : '',
		'SCROLLTOTOP_POSITION_BOTTOM' : '',
		'ONE_CLICK_BUY_CAPTCHA' : 'N',
		'USE_INTL_PHONE' : 'N',
		'PHONE_MASK' : '+7 (999) 999-99-99',
		'VALIDATE_PHONE_MASK' : '^[+][0-9] [(][0-9]{3}[)] [0-9]{3}[-][0-9]{2}[-][0-9]{2}$',
		'DATE_MASK' : 'dd.mm.yyyy',
		'DATE_PLACEHOLDER' : 'дд.мм.гггг',
		'VALIDATE_DATE_MASK' : '^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{4}$',
		'DATETIME_MASK' : 'dd.mm.yyyy h:s',
		'DATETIME_PLACEHOLDER' : 'дд.мм.гггг чч:мм',
		'VALIDATE_DATETIME_MASK' : '^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{4} [0-9]{1,2}\:[0-9]{1,2}$',
		'VALIDATE_FILE_EXT' : 'png|jpg|jpeg|gif|doc|docx|xls|xlsx|txt|pdf|odt|rtf',
		'BIGBANNER_ANIMATIONTYPE' : 'SLIDE_HORIZONTAL',
		'BIGBANNER_SLIDESSHOWSPEED' : '5000',
		'BIGBANNER_ANIMATIONSPEED' : '600',
		'PARTNERSBANNER_SLIDESSHOWSPEED' : '5000',
		'PARTNERSBANNER_ANIMATIONSPEED' : '600',
		'ORDER_BASKET_VIEW' : 'FLY2',
		'SHOW_BASKET_ONADDTOCART' : 'Y',
		'SHOW_BASKET_PRINT' : 'Y',
		'SHOW_SHARE_BASKET' : 'N',
		"SHOW_DOWNLOAD_BASKET" : 'N',
		"BASKET_FILE_DOWNLOAD_TEMPLATE" : 'xls',
		"SHOW_ONECLICKBUY_ON_BASKET_PAGE" : 'Y',
		'SHOW_LICENCE' : 'Y',
		'LICENCE_CHECKED' : 'Y',
		'SHOW_OFFER' : 'N',
		'OFFER_CHECKED' : 'N',
		'LOGIN_EQUAL_EMAIL' : 'Y',
		'PERSONAL_ONEFIO' : 'Y',
		'SHOW_TOTAL_SUMM' : 'N',
		'SHOW_TOTAL_SUMM_TYPE' : 'CHANGE',
		'CHANGE_TITLE_ITEM_LIST' : 'N',
		'CHANGE_TITLE_ITEM_DETAIL' : 'N',
		'DISCOUNT_PRICE' : '',
		'STORES_SOURCE' : 'IBLOCK',
		'TYPE_SKU' : 'TYPE_1',
		'MENU_POSITION' : 'LINE',
		'MENU_TYPE_VIEW' : 'HOVER',
		'DETAIL_PICTURE_MODE' : 'POPUP',
		'PAGE_WIDTH' : '3',
		'PAGE_CONTACTS' : '1',
		'HEADER_TYPE' : '17',
		'REGIONALITY_SEARCH_ROW' : 'N',
		'HEADER_FIXED' : '3',
		'HEADER_MOBILE' : '1',
		'HEADER_MOBILE_MENU' : '1',
		'TYPE_SEARCH' : 'fixed',
		'PAGE_TITLE' : '4',
		'INDEX_TYPE' : 'index1',
		'FOOTER_TYPE' : '1',
		'PRINT_BUTTON' : 'N',
		'USE_LAZY_LOAD' : 'N',
		'EXPRESSION_FOR_PRINT_PAGE' : 'Версия для печати',
		'EXPRESSION_FOR_FAST_VIEW' : 'Быстрый просмотр',
		'EXPRESSION_FOR_SHARE_BASKET' : 'Поделиться корзиной',
		'EXPRESSION_FOR_DOWNLOAD_BASKET' : 'Скачать файлом',
		'FILTER_VIEW' : 'COMPACT',
		'YA_GOALS' : 'Y',
		'YA_COUNTER_ID' : '57532333',
		'USE_FORMS_GOALS' : 'SINGLE',
		'USE_BASKET_GOALS' : 'Y',
		'USE_DEBUG_GOALS' : 'N',
		'SHOW_HEADER_GOODS' : 'Y',
		'INSTAGRAMM_INDEX' : 'N',
		'USE_PHONE_AUTH': 'N',
		'MOBILE_CATALOG_LIST_ELEMENTS_COMPACT': 'Y',
		'STICKY_SIDEBAR': 'N',
		'REVIEWS_VIEW': 'EXTENDED',
		'MANY_BUY_CATALOG_SECTIONS': 'Y',
		'FIXED_BUY_MOBILE': 'N',
	}),
	"REGIONALITY":({
		'USE_REGIONALITY' : 'Y',
		'REGIONALITY_VIEW' : 'POPUP_REGIONS_SMALL',
	}),
	"COUNTERS":({
		"YANDEX_COUNTER" : 1,
		"GOOGLE_COUNTER" : 1,
		"YANDEX_ECOMERCE" : "Y",
		"GOOGLE_ECOMERCE" : "Y",
		"GA_VERSION" : "v3",
		"TYPE":{
			"ONE_CLICK":"Купить в 1 клик",
			"QUICK_ORDER":"Быстрый заказ",
		},
		"GOOGLE_EVENTS":{
			"ADD2BASKET": "addToCart",
			"REMOVE_BASKET": "removeFromCart",
			"CHECKOUT_ORDER": "checkout",
			"PURCHASE": "gtm.dom",
		}
	}),
	"JS_ITEM_CLICK":({
		"precision" : 6,
		"precisionFactor" : Math.pow(10,6)
	})
});